/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as PetEditImport } from './routes/pet-edit'
import { Route as PetDetailsImport } from './routes/pet-details'
import { Route as OrgsImport } from './routes/orgs'
import { Route as OrgEditImport } from './routes/org-edit'
import { Route as OrgDetailsImport } from './routes/org-details'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const PetEditRoute = PetEditImport.update({
  path: '/pet-edit',
  getParentRoute: () => rootRoute,
} as any)

const PetDetailsRoute = PetDetailsImport.update({
  path: '/pet-details',
  getParentRoute: () => rootRoute,
} as any)

const OrgsRoute = OrgsImport.update({
  path: '/orgs',
  getParentRoute: () => rootRoute,
} as any)

const OrgEditRoute = OrgEditImport.update({
  path: '/org-edit',
  getParentRoute: () => rootRoute,
} as any)

const OrgDetailsRoute = OrgDetailsImport.update({
  path: '/org-details',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/org-details': {
      id: '/org-details'
      path: '/org-details'
      fullPath: '/org-details'
      preLoaderRoute: typeof OrgDetailsImport
      parentRoute: typeof rootRoute
    }
    '/org-edit': {
      id: '/org-edit'
      path: '/org-edit'
      fullPath: '/org-edit'
      preLoaderRoute: typeof OrgEditImport
      parentRoute: typeof rootRoute
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsImport
      parentRoute: typeof rootRoute
    }
    '/pet-details': {
      id: '/pet-details'
      path: '/pet-details'
      fullPath: '/pet-details'
      preLoaderRoute: typeof PetDetailsImport
      parentRoute: typeof rootRoute
    }
    '/pet-edit': {
      id: '/pet-edit'
      path: '/pet-edit'
      fullPath: '/pet-edit'
      preLoaderRoute: typeof PetEditImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org-details': typeof OrgDetailsRoute
  '/org-edit': typeof OrgEditRoute
  '/orgs': typeof OrgsRoute
  '/pet-details': typeof PetDetailsRoute
  '/pet-edit': typeof PetEditRoute
  '/signin': typeof SigninRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org-details': typeof OrgDetailsRoute
  '/org-edit': typeof OrgEditRoute
  '/orgs': typeof OrgsRoute
  '/pet-details': typeof PetDetailsRoute
  '/pet-edit': typeof PetEditRoute
  '/signin': typeof SigninRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org-details': typeof OrgDetailsRoute
  '/org-edit': typeof OrgEditRoute
  '/orgs': typeof OrgsRoute
  '/pet-details': typeof PetDetailsRoute
  '/pet-edit': typeof PetEditRoute
  '/signin': typeof SigninRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/org-details'
    | '/org-edit'
    | '/orgs'
    | '/pet-details'
    | '/pet-edit'
    | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/org-details'
    | '/org-edit'
    | '/orgs'
    | '/pet-details'
    | '/pet-edit'
    | '/signin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/org-details'
    | '/org-edit'
    | '/orgs'
    | '/pet-details'
    | '/pet-edit'
    | '/signin'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrgDetailsRoute: typeof OrgDetailsRoute
  OrgEditRoute: typeof OrgEditRoute
  OrgsRoute: typeof OrgsRoute
  PetDetailsRoute: typeof PetDetailsRoute
  PetEditRoute: typeof PetEditRoute
  SigninRoute: typeof SigninRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrgDetailsRoute: OrgDetailsRoute,
  OrgEditRoute: OrgEditRoute,
  OrgsRoute: OrgsRoute,
  PetDetailsRoute: PetDetailsRoute,
  PetEditRoute: PetEditRoute,
  SigninRoute: SigninRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/org-details",
        "/org-edit",
        "/orgs",
        "/pet-details",
        "/pet-edit",
        "/signin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/org-details": {
      "filePath": "org-details.tsx"
    },
    "/org-edit": {
      "filePath": "org-edit.tsx"
    },
    "/orgs": {
      "filePath": "orgs.tsx"
    },
    "/pet-details": {
      "filePath": "pet-details.tsx"
    },
    "/pet-edit": {
      "filePath": "pet-edit.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
